### PR TITLE
Add properties to set the class of input and div wrapper.

### PR DESCRIPTION
**Pull request by Dexesttp**
# Scope

Solves #3 

Adds a `wrapperClass`, `inputClass` and `listClass` parameter to set the wrapper, input and list classes respectively.

## Code

```html
<autocomplete
    inputClass="input"
    wrapperClass="wrapper"
    listClass="list">
</autocomplete>
```

### CODE REVIEW

**Comment by Dexesttp** [comment]
`className` sets the wrapper and the input as `<classname>-wrapper` and `<classname>-input` respectively, but is not able to set a specific class name to the given tags.

The original use case for this pull request was to set an exact bootstrap class for the input, and I though it'd be a good idea to add the option to the wrapper too. I should actually have included an option to set the list class explicitly.

Another idea may be to factorize setting classes. We could do that by passing an object with several keys instead of having a specific property for each component.

```html
<autocomplete
    :classes="{ wrapper: 'wrapperClass', input: 'inputClass', list: {listClass1: true, listClass2: false} }">
</autocomplete>
```

**Comment by jakobrosenberg** [comment]
I think that would add another level of verbosity with little to no benefits. :)

**Comment by silkyland** [comment]
Please merge this to master

**Comment by BosNaufal** [comment]
Hi @Dexesttp 
Thanks for giving me a pull request. But sorry, i haven't yet checked your PR before I updated the package. and fortunately this feature has been added. So, please Check our new autocomplete. 

Thank you all for your ideas! @Dexesttp @jakobrosenberg @silkyland

**Pull request closed without merging**
